baseurl = "https://xiangyun.rbind.io/"
languageCode = "zh-CN"
title = "Xiangyun Huang"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "类别"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"
[[menu.main]]
    name = "文章"
    url = "/archives/"
    weight = 5
[[menu.main]]
    name = "简历"
    url = "/resume/"
    weight = 6

[[menu.main]]
    name = "友链"
    url = "/blog/"
    weight = 7

[params]
    description = "网站由 Hugo 和 blogdown 强力驱动"
    summary_length = 200
    github_edit = "https://github.com/XiangyunHuang/xiangyun/edit/master/content/"
    footer = "&copy; [黄湘云](https://xiangyun.rbind.io/) 2016 - 2020 | [Github](https://github.com/XiangyunHuang) | [推特](https://twitter.com/StatCloud) | [爆栈网](https://stackoverflow.com/users/8278176) | [新浪微博](https://weibo.com/Cloud2016)"
    enableGitalk = true

[params.text]
    back = "&larr; 回到主页"
    edit = "编辑页面 &rarr;"
    truncated = "&hellip;"
    tags = "关键词："
    uncategorized = "未分类"
    title_categories = "栏目分类"
    title_tags = "关键词列表"

[markup]
    [markup.goldmark.renderer]
      unsafe = true

[params.gitalk]
    clientID = "9dfb233f53abb0becfb5" # Your client ID
    clientSecret = "474d2587fac0a1743feda3d5b1325899de3d8d56" # Your client secret
    repo = "xiangyun" # The repo to store comments
    owner = "XiangyunHuang" # Your GitHub ID
    admin = "XiangyunHuang" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id = "location.pathname" # The unique id of the page.
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment
