baseurl = "https://xiangyun.rbind.io/"
languageCode = "zh-CN"
title = "Xiangyun Huang"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "类别"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"
[[menu.main]]
    name = "文章"
    url = "/archives/"
    weight = 5
[[menu.main]]
    name = "简历"
    url = "/resume/"
    weight = 6

[[menu.main]]
    name = "友链"
    url = "/blog/"
    weight = 7

[params]
    description = "网站由 [Hugo](https://github.com/gohugoio/hugo) 和 [blogdown](https://github.com/rstudio/blogdown) 强力驱动"
    summary_length = 200
    github_edit = "https://github.com/XiangyunHuang/xiangyun/edit/master/content/"
    footer = "&copy; [黄湘云](https://xiangyun.rbind.io/) 2016 - 2020 | [Github](https://github.com/XiangyunHuang) | [推特](https://twitter.com/StatCloud) | [爆栈网](https://stackoverflow.com/users/8278176) | [新浪微博](https://weibo.com/Cloud2016)"

[params.text]
    back = "&larr; 回到主页"
    edit = "编辑页面 &rarr;"
    truncated = "&hellip;"
    tags = "关键词："
    uncategorized = "未分类"
    title_categories = "栏目分类"
    title_tags = "关键词列表"

[markup]
    [markup.goldmark.renderer]
      unsafe = true
