baseurl = "https://xiangyun.rbind.io/"
languageCode = "zh-CN"
title = "Xiangyun Huang"
theme = "hugo-lithium"
googleAnalytics = "UA-115387038-3"
disqusShortname = "disqus_4zEgdFh5L6"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."

    customCSS = ["css/custom.css"]
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

[markup]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      codeFences = false
    [markup.tableOfContents]
      startLevel = 1
